fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
        files: \.toml$
      - id: check-yaml
        files: \.yaml$        
      - id: check-json
        files: \.json$
        exclude: ^python\/.vscode\/.*
      - id: end-of-file-fixer
        files: \.py$
      - id: mixed-line-ending
        files: \.py$
      - id: debug-statements
        files: ^semantic_kernel\/.*\.py$
      - id: check-ast
        name: Check Valid Python Samples
        types: ["python"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-check-ast
        name: Check Valid Python Notebooks
        types: ["jupyter"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    - id: pyupgrade
      args: [--py310-plus]
  - repo: local
    hooks:
      - id: ruff
        files: ^semantic_kernel/
        name: ruff
        entry: uv tool run ruff check semantic_kernel --fix --exit-non-zero-on-fix
        language: system
        types: [python]
  - repo: local
    hooks:
    - id: mypy
      files: ^semantic_kernel/
      name: mypy
      entry: uv tool run python -m mypy -p semantic_kernel
      language: system
      types: [python]
      pass_filenames: false
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-c", "python/pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]