[tool.poetry]
name = "semantic-kernel"
version = "0.9.1b1"
description = "Semantic Kernel Python SDK"
authors = ["Microsoft <SK-Support@microsoft.com>"]
readme = "pip/README.md"
packages = [{include = "semantic_kernel"}]

[tool.poetry.dependencies]
python = "^3.8,<3.13"
aiohttp = "^3.8"
numpy = [
    { version = "^1.24", python = "3.8" },
    { version = ">=1.25", python = ">=3.9,<3.12" },
    { version = ">=1.26", python = ">=3.12" },
]
scipy = [
    { version = ">=1.5.0", python = "<3.12" },
    { version = ">=1.12.0", python = ">=3.12" }
]
grpcio = [
    { version = ">=1.40.0", python = "3.8" },
    { version = ">=1.50.0", python = ">=3.9" },
    { version = ">=1.60.0", python = ">=3.12" }
]
openai = ">=1.0"
python-dotenv = "^1.0.1"
regex = "^2023.6.3"
openapi_core = "^0.18.0"
prance = "^23.6.21.0"
pydantic = "^2"
motor = "^3.3.2"
defusedxml = "^0.7.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
black = "^23.12.0"
ruff = "^0.3.0"
ipykernel = "^6.21.1"
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
snoop = "^0.4.3"
pytest-cov = ">=4.1.0"
mypy = ">=1.8.0"

[tool.poetry.group.google_palm.dependencies]
google-generativeai = { version = ">=0.1", markers = "python_version >= '3.9'" }

[tool.poetry.group.hugging_face.dependencies]
transformers = "^4.28.1"
sentence-transformers = "^2.2.2"
torch = "^2.2.0"

[tool.poetry.group.qdrant.dependencies]
qdrant-client = [
    { version = '^1.6', python = '3.8' },
    { version = '>=1.7', python = '>3.9' }
]

[tool.poetry.group.chromadb.dependencies]
chromadb = "^0.4.13"

[tool.poetry.group.milvus.dependencies]
pymilvus = [
    { version = "^2.2,<2.3", markers = 'python_version == "3.8"'},
    { version = ">=2.3,<2.3.8", markers = 'python_version > "3.8"'}
]
milvus = [
    { version = "^2.2,<2.3", markers = 'python_version == "3.8" and sys_platform != "win32"'},
    { version = ">=2.3,<2.3.8", markers = 'python_version > "3.8" and sys_platform != "win32"'}
]

[tool.poetry.group.weaviate.dependencies]
weaviate-client = ">=3.18,<5.0"

[tool.poetry.group.pinecone.dependencies]
pinecone-client = "^2.2.2"

[tool.poetry.group.postgres.dependencies]
psycopg = { version="^3.1.9", extras=["binary","pool"]}

[tool.poetry.group.redis.dependencies]
redis = "^4.6.0"

[tool.poetry.group.azure_cognitive_search.dependencies]
azure-search-documents = {version = "11.6.0b1", allow-prereleases = true}
azure-core = "^1.28.0"
azure-identity = "^1.13.0"

[tool.poetry.group.tests.dependencies]
azure-search-documents = {version = "11.6.0b1", allow-prereleases = true}
azure-core = "^1.28.0"

[tool.poetry.group.usearch.dependencies]
usearch = "^2.9"
pyarrow = ">=12.0.1,<15.0.0"

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
