name: Python post coverage comment

on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]


jobs:
  post_coverage_comment:
    needs: python-unit-tests
    runs-on: ubuntu-latest
    # This job runs if the triggering workflow was for a pull_request event and concluded successfully.
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'java-development')
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download coverage report artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Post coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PR_WRITE }}
