name: Python Unit Tests

on:
  pull_request:
    branches: ["main", "feature*"]
    paths:
      - "python/**"

jobs:
  python-unit-tests:
    uses: ./python/.github/actions/python-unit-tests.yml
    secrets: inherit
